# This file contains values from Cookiecutter

default_context:
  project_name: "quant_interface"
  project_description: "A modualar backtesting wrapper for quant algorithms"
  organization: "Douglas Schonholtz"
  license: "MIT"
  minimal_python_version: 3.10
  github_name: "dschonholtz"
  email: "schonholtzd@gmail.com"
  version: "0.1.0"
  line_length: "79"
  create_example_template: "none"
